/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package obligatorio;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gpaz1
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Adminstrador
     */
    public  String app_id ="";
    public void cargarUsers() {
        String sql = "SELECT * FROM obligatorioDB.PERMISOS WHERE estado = 'pendiente';";

        String columnas[] = {"user_id", "app_id", "rol_neg_id", "fecha_solicitud", "fecha_autorizacion", "estado"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        String[] registros = new String[6];
        try {
            Statement stat = conec.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("user_id");
                registros[1] = rs.getString("app_id");
                registros[2] = rs.getString("rol_neg_id");
                registros[3] = rs.getString("fecha_solicitud");
                registros[4] = rs.getString("fecha_autorizacion");
                registros[5] = rs.getString("estado");

                modelo.addRow(registros);
            }
            tblUser.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Loggin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(772, 401));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        tblUser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_number", "Nombre", "Apellido", "Rol", "Fecha_Ingreso", "Contacto"
            }
        ));
        tblUser.setRowHeight(23);
        jScrollPane1.setViewportView(tblUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 660, 140));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setText("Administradores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jButton1.setText("AUTORIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, 40));

        jButton2.setText("Modificar Rol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 170, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-login-web.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 400));
    }// </editor-fold>//GEN-END:initComponents
public String fechaActual() {

        String timestamp = ZonedDateTime.now(ZoneId.of("America/Montevideo"))
                .format(DateTimeFormatter.ofPattern("MM-dd-yyy"));
        String fecha = timestamp;
        return fecha;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(), 0));

        String sql = "UPDATE `obligatorioDB`.`PERMISOS` SET `estado` = 'Aprobado', fecha_autorizacion = '" + fechaActual() + "' WHERE (`user_id` ="
                + " '" + user + "')";
        try {
            PreparedStatement pst = conec.prepareStatement(sql);
            pst.executeUpdate();

            cargarUsers();
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String user = String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(), 0));
        Object seleccion = JOptionPane.showInputDialog(null,
                "Seleccione rol",
                "Selector de Roles",
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono defecto
                new Object[]{"Administrador","encargado", "jefe", "empleado"}, "Administrador");
               
                if(seleccion.toString().contains("administrador")){
                    app_id="adm_app";
                    
                }
                if(seleccion.toString().contains("encargado")){
                    app_id="enc_app";
                    
                }
                if(seleccion.toString().contains("jefe")){
                    app_id="jef_app";
                   
                }
                if(seleccion.toString().contains("empleado")){
                    app_id="emp_app";
                    
                }
        String sql = "UPDATE `obligatorioDB`.`PERMISOS` SET `rol_neg_id`='" + seleccion + "', app_id='"+app_id+"', `estado` = 'Aprobado', fecha_autorizacion = '" + fechaActual() + "' WHERE (`user_id` ="
                + " '" + user + "')";
        try {
            PreparedStatement pst = conec.prepareStatement(sql);
            pst.executeUpdate();

            cargarUsers();
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
    Conexion_MySql conexion = new Conexion_MySql();
    Connection conec = conexion.ConectarBasedeDatos();
}
