/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatorio;

/**
 *
 * @author gpaz1
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Profesores
     */
    public void CargaUser(){
        backround.setOpaque(true);
        lblname.setText(Loggin.user);
        lblrol.setText("ROL: "+ Loggin.rolUser);
    }
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargaUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblrol = new javax.swing.JLabel();
        lbliconuser = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(831, 520));
        setMinimumSize(new java.awt.Dimension(831, 520));
        setPreferredSize(new java.awt.Dimension(831, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Administrador");
        jButton1.setActionCommand("btnPrincipal");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 40));

        lblrol.setForeground(new java.awt.Color(255, 255, 255));
        lblrol.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 160, 30));

        lbliconuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbliconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoUser.png"))); // NOI18N
        getContentPane().add(lbliconuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        lblname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 30));

        backround.setBackground(new java.awt.Color(0, 101, 169));
        backround.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 220, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backround;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbliconuser;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblrol;
    // End of variables declaration//GEN-END:variables
}
