/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatorio;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author gpaz1
 */
public class RecuperacionPassword extends javax.swing.JFrame {

    public void cargaPregunta() {

        try {
            Statement obtenerRolSeleccionado = conec.createStatement();
            ResultSet rol = obtenerRolSeleccionado.executeQuery("SELECT obligatorioDB.PERSONAS_PREGUNTAS.preg_id FROM "
                    + "obligatorioDB.PERSONAS_PREGUNTAS WHERE user_id = '" + Loggin.ci + "';");

            if (rol.next()) {
                String numPreg = rol.getString("preg_id");
                ResultSet pregunta = obtenerRolSeleccionado.executeQuery("SELECT obligatorioDB.PREGUNTAS.preguntas FROM "
                        + "obligatorioDB.PREGUNTAS WHERE preg_id = '" + numPreg + "';");
                if (pregunta.next()) {
                    this.pregunta.setText(pregunta.getString("preguntas"));
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Datos Erroneos Reintene", "", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }

    /**
     * Creates new form Materias
     */
    public RecuperacionPassword() {
        initComponents();
        cargaPregunta();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pregunta = new javax.swing.JLabel();
        respuesta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 374));
        setMinimumSize(new java.awt.Dimension(400, 374));
        setPreferredSize(new java.awt.Dimension(400, 374));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        validar.setText("VALIDAR RESPUESTA");
        validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarActionPerformed(evt);
            }
        });
        getContentPane().add(validar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 30));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECUPERACION DE CONTRASEÑA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 40));
        getContentPane().add(pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 40));
        getContentPane().add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarActionPerformed
        String resp = respuesta.getText();
        try {
            Statement obtenerRolSeleccionado = conec.createStatement();
            ResultSet rol = obtenerRolSeleccionado.executeQuery("SELECT obligatorioDB.PERSONAS_PREGUNTAS.respuesta FROM "
                    + "obligatorioDB.PERSONAS_PREGUNTAS WHERE user_id = '" + Loggin.ci + "';");

            if (rol.next()) {
                String answ = rol.getString("respuesta");
                if (answ.contains(resp)) {

                    String pass = JOptionPane.showInputDialog("Respuesta Correcta, ingrese su nueva Contraseña");
                    String sql = "UPDATE `obligatorioDB`.`PERSONAS` SET `hashpwd` = '" + Loggin.hashPwd(pass) + "' WHERE (`user_id` ="
                            + " '" + Loggin.ci + "')";
                    PreparedStatement pst = conec.prepareStatement(sql);
                    pst.executeUpdate();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "RESPUESTA INCORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

//          ResultSet pregunta = obtenerRolSeleccionado.executeQuery("SELECT obligatorioDB.PREGUNTAS.preguntas FROM "
//                + "obligatorioDB.PREGUNTAS WHERE preg_id = '" + numPreg + "';");
//          if(pregunta.next()){
//              this.pregunta.setText(pregunta.getString("preguntas"));
//          }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Datos Erroneos Reintene", "", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_validarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pregunta;
    private javax.swing.JTextField respuesta;
    private javax.swing.JButton validar;
    // End of variables declaration//GEN-END:variables
Conexion_MySql conexion = new Conexion_MySql();
    Connection conec = conexion.ConectarBasedeDatos();
}
